version: '2'
services:
  server:
    image: ipepe/pnpr:v3-u2004-r2.7.5-n10-staging
    environment:
      PGPASSWORD: Password1
    links:
      - postgres_db
    ports:
      - "1022:22"
      - "1080:80"
    network_mode: bridge
    volumes:
      - ./data/webapp:/home/webapp/webapp
      - ./data/ssh:/home/webapp/.ssh
    labels:
      - 'traefik.enable=true'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:staging.example.org'

  postgres_db:
    network_mode: bridge
    image: postgres:14
    environment:
      POSTGRES_DB: webapp
      POSTGRES_USER: webapp
      POSTGRES_PASSWORD: Password1
    expose:
      - 5432

# docker-compose -f docker-compose.staging.yml up --build