version: '3.2'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - docker.io/ipepe/pnpr:v3-u2004-r2.7.5-n10-staging
      args:
        - RAILS_ENV=staging
        - RUBY_VERSION=2.7.5
        - NODE_MAJOR_VERSION=10
    environment:
      PGPASSWORD: Password1
    ports:
      - "1022:22"
      - "1080:80"
      - "9149:9149"
    volumes:
      - /dev/null:/etc/systemd/system/sidekiq.service
      - ./data/webapp:/home/webapp/webapp
      - ./data/ssh:/home/webapp/.ssh
    links:
      - postgres_db
    network_mode: bridge

  postgres_db:
    network_mode: bridge
    image: postgres:14
    environment:
      POSTGRES_DB: webapp
      POSTGRES_USER: webapp
      POSTGRES_PASSWORD: Password1
    expose:
      - 5432

# docker-compose -f docker-compose.dev.yml up --build