name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.3.1', '2.3.8', '2.4.10', '2.5.9', '2.6.10', '2.7.2', '2.7.5', '2.7.6', '2.7.7', '3.0.4', '3.0.5', '3.1.2', '3.1.3']
        node-version: ['10','12','14','16','18']
        env-level: ['production', 'staging', 'development']
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image for ruby-${{ matrix.ruby-version }} and node-${{ matrix.node-version }}
      run: docker build docker --file docker/Dockerfile --tag ipepe/pnpr:v3-u2004-r${{ matrix.ruby-version }}-n${{ matrix.node-version }}-${{ matrix.env-level }} --build-arg RUBY_VERSION=#{ruby_version} --build-arg NODE_MAJOR_VERSION=${{ matrix.node-version }} --build-arg RAILS_ENV=${{ matrix.env-level }}
    - name: Publish the Docker image
      run: docker push ipepe/pnpr:v3-u2004-r${{ matrix.ruby-version }}-n${{ matrix.node-version }}-${{ matrix.env-level }}